---
title: "testing overflow properties"
description: |
  A short description of the post.
author:
  - name: Roland Schmidt
    url: https://werk.statt.codes
date: 12-31-2020
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
    highlight: haddock
    highlight_downlit: true

draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

long code chunk

```{r, eval=F}
fn_reactable_headings <- function(title, subtitle, body, caption) {
  div(class="reactable-table",
      div(
        class="reactable-title",
        title
      ),
      div(
        class="reactable-subtitle",
        subtitle
      ),
      # div(
        #class="reactable-body",
        body
        # )
      ,
      div(
        class="reactable-caption",
        caption
      )
  )
}


rt_theme <- reactableTheme(backgroundColor = plot_bg_color,
                           style=list(fontFamily="Karla",
                                      fontSize="12px"),
                           filterInputStyle = list(
                             color="green",
                             backgroundColor = plot_bg_color))

```






```{r, eval=FALSE}
#dfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#dfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#dfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#


```


plot

```{r}
plot_bg_color <- readr::read_file(file=here::here("theme.css")) %>% 
  str_extract(., regex("(?<=background-color:).*?(?=;)")) %>% str_trim()


library(tidyverse)
mtcars %>% 
  ggplot()+
  geom_point(aes(x=mpg,
                 y=cyl))+
  theme(plot.background = element_rect(fill=plot_bg_color))
  
```
# heading 1

test test

## heading 2

test test

### heading 3

text text



```{r}
library(reactable)
mtcars %>% 
  reactable(., 
            defaultPageSize = 4, 
          # columns = list(
          #   link_single_submission_page = colDef(
          #     cell = function(value) {
          #       url <- value
          #       htmltools::tags$a(href = url, 
          #                         target = "_blank", 
          #                         value)
          #       },
          #     width = 150,
          #     html=TRUE
          #     )),
          filterable = TRUE,
          bordered=TRUE,
          compact = TRUE,
          style = list(fontSize = "10px"),
          theme = reactableTheme(
            backgroundColor = "#f0eff0",
                filterInputStyle = list(
                  color="green",
                  backgroundColor = "#f0eff0")))
```

